name = "osteoflow-survey"
main = "src/index.ts"
compatibility_date = "2024-02-08"

[[kv_namespaces]]
binding = "SURVEYS"
id = "72393482345d45d5a103bea6928bcaaa"
preview_id = "320037bb037e4dabbdbac1e0fba16143"

[vars]
# Optional: restrict API calls to known app instances
# API_SECRET = "change-me-in-production"
